services:
  - type: web
    name: spotbulle-ia-v2
    env: node
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "cd backend && NODE_ENV=production PORT=10000 node src/server-with-frontend.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BUCKET_NAME
        value: "pitch-videos"
      - key: FRONTEND_URL
        value: "https://spotbulle-ia-v2.onrender.com"
      - key: NEXT_PUBLIC_API_URL
        value: "https://spotbulle-ia-v2.onrender.com"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health

databases:
  - name: spotbulle-ia-db-v2
    plan: basic-256mb

