services:
  - type: web
    name: spotbulle-ia
    env: node
    plan: starter
    # SOLUTION IMMEDIATE - Forcer un nouveau build en modifiant la commande
    buildCommand: "echo 'CACHE_BUST_2025_07_01' && ./build.sh"
    startCommand: |
      echo "🚀 Démarrage SpotBulle IA..."
      export NODE_ENV=production
      export PORT=10000
      export NODE_OPTIONS="--max-old-space-size=2048"
      
      if [ ! -f "backend/src/server-with-frontend.js" ]; then
        echo "❌ Serveur manquant"
        exit 1
      fi
      
      cd backend && node src/server-with-frontend.js
      
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BUCKET_NAME
        value: "pitch-videos"
      - key: FRONTEND_URL
        value: "https://spotbulle-ia.onrender.com"
      - key: NEXT_PUBLIC_API_URL
        value: "https://spotbulle-ia.onrender.com"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
        
    healthCheckPath: /health
    
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - build.sh
        - render.yaml
      ignoredPaths:
        - "**/*.md"
        - "**/node_modules/**"
        - "**/.git/**"

databases:
  - name: spotbulle-ia-db
    plan: basic-256mb

