services:
  # Service principal avec frontend et backend intégrés
  - type: web
    name: spotbulle-ia
    env: node
    plan: starter
    buildCommand: |
      # Installer les dépendances du backend
      cd backend && npm install &&
      # Installer les dépendances du frontend
      cd ../frontend && npm install &&
      # Build du frontend Next.js
      npm run build &&
      # Retourner au répertoire racine
      cd ..
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # Ou true si vous utilisez un groupe de secrets
      - key: JWT_SECRET
        value: |-
          #!/usr/bin/env bash
          node backend/generate_jwt_secret.js
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BUCKET_NAME
        value: "pitch-videos"
      - key: FRONTEND_URL
        value: "https://spotbulle-ia.onrender.com"
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: spotbulle-ia-db
    plan: basic-256mb
