services:
  # Service principal avec frontend et backend intégrés
  - type: web
    name: spotbulle-ia
    env: node
    plan: starter
    buildCommand: "./build.sh"
    startCommand: |
      echo "🚀 Démarrage du serveur SpotBulle IA..."
      export NODE_ENV=production
      export PORT=10000
      export NODE_OPTIONS="--max-old-space-size=2048"
      
      # Vérifier que les fichiers nécessaires existent
      if [ ! -f "backend/src/server-with-frontend.js" ]; then
        echo "❌ Fichier serveur manquant"
        exit 1
      fi
      
      if [ ! -d "frontend/.next" ]; then
        echo "⚠️ Build Next.js manquant, démarrage en mode dégradé"
      fi
      
      # Démarrer le serveur
      cd backend && node src/server-with-frontend.js
      
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BUCKET_NAME
        value: "pitch-videos"
      - key: FRONTEND_URL
        value: "https://spotbulle-ia.onrender.com"
      - key: NEXT_PUBLIC_API_URL
        value: "https://spotbulle-ia.onrender.com"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
        
    # Configuration des health checks
    healthCheckPath: /health
    
    # Configuration des variables de build
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - build.sh
        - render.yaml
      ignoredPaths:
        - "**/*.md"
        - "**/node_modules/**"
        - "**/.git/**"
        - "**/coverage/**"
        - "**/.next/**"

databases:
  - name: spotbulle-ia-db
    plan: basic-256mb

